# Generated by Django 3.1.7 on 2021-04-19 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=50)),
                ('class_name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('class_id', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(blank=True, related_name='students', to='accounts.StudentUser')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='accounts.teacheruser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True, verbose_name='Вопрос')),
                ('question_type', models.CharField(blank=True, choices=[('text', 'text'), ('check box', 'check box'), ('multiple choice', 'multiple choice')], max_length=50, null=True, verbose_name='Тип вопроса')),
                ('answers', models.ManyToManyField(blank=True, null=True, to='classes.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(to='classes.Question')),
                ('scratch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scratch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scratch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('due_date', models.DateTimeField()),
                ('points', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scratch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Announcment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='')),
                ('annoucment_text', models.TextField()),
                ('announce_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scratch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AboutClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.CharField(choices=[('english', 'english'), ('russian', 'russian'), ('kazakh', 'kazakh')], max_length=50)),
                ('about_course', models.TextField()),
                ('scratch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
