# Generated by Django 3.1.7 on 2021-04-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210419_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='homeworkmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='lessonmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='materialmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quizmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='announcment',
            name='announce_time',
        ),
        migrations.AlterField(
            model_name='announcment',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
