# Generated by Django 3.1.7 on 2021-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210420_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutclass',
            name='syllabus',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
