# Generated by Django 3.1.7 on 2021-05-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210430_1546'),
        ('classes', '0007_remove_homeworkmodel_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='user_students', to='accounts.StudentUser'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to='accounts.teacheruser'),
        ),
    ]
