# Generated by Django 3.1.7 on 2021-05-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20210511_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='class_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
