# Generated by Django 3.1.7 on 2021-05-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_classmodel_class_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcment',
            name='uploaded_file',
        ),
    ]
