# Generated by Django 3.1.7 on 2021-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20210511_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutclass',
            name='syllabus',
            field=models.JSONField(),
        ),
    ]
