# Generated by Django 3.1.7 on 2021-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_auto_20210513_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='about_course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='syllabus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
