# Generated by Django 3.1.7 on 2021-04-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkcomments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizcomments',
            options={},
        ),
    ]
