# Generated by Django 3.1.7 on 2021-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20210511_1415'),
        ('classes', '0009_auto_20210511_1415'),
        ('accounts', '0002_auto_20210430_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='specific_field',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='TeacherUser',
        ),
    ]
