# Generated by Django 3.1.7 on 2021-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20210422_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitquiz',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
