# Generated by Django 3.1.7 on 2021-04-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('submissions', '0004_auto_20210424_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_homework', to='accounts.studentuser'),
        ),
        migrations.AlterField(
            model_name='submitquiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_quizes', to='accounts.studentuser'),
        ),
    ]
