# Generated by Django 3.1.7 on 2021-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20210424_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='grade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitquiz',
            name='grade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
