# Generated by Django 3.1.7 on 2021-05-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20210509_1408'),
        ('submissions', '0007_auto_20210424_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_homework', to='classes.homeworkmodel'),
        ),
        migrations.AlterField(
            model_name='submitquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_quiz', to='classes.quizmodel'),
        ),
    ]
