# Generated by Django 3.1.7 on 2021-05-11 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0008_auto_20210509_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submithomework',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_homework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submitquiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_quizes', to=settings.AUTH_USER_MODEL),
        ),
    ]
